echo "myhelp - this"
echo "pycode - change directory to python programming directory"
echo "getip - gets your public ip"
echo "segfault - create a new connection to segfault.net"
echo "scriptshow - opens script directory"
